# Generated by Django 4.2.10 on 2024-02-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoe', '0003_rename_created_by_shoe_updated_at_alter_shoe_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
