# Generated by Django 4.2.10 on 2024-02-20 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoe', '0004_alter_shoe_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentShoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Напиши свое мнение о товаре')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shoe_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='shoe.shoe')),
            ],
        ),
    ]
