# Generated by Django 4.2.10 on 2024-02-20 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoe', '0005_commentshoe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentshoe',
            name='shoe_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='shoe.shoe'),
        ),
    ]
